//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34014
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISQLWebService", CallbackContract=typeof(ISQLWebServiceCallback))]
public interface ISQLWebService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQLWebService/SetClientCallbackProxy", ReplyAction="http://tempuri.org/ISQLWebService/SetClientCallbackProxyResponse")]
    void SetClientCallbackProxy();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQLWebService/SetClientCallbackProxy", ReplyAction="http://tempuri.org/ISQLWebService/SetClientCallbackProxyResponse")]
    System.Threading.Tasks.Task SetClientCallbackProxyAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQLWebService/SetDBConnection", ReplyAction="http://tempuri.org/ISQLWebService/SetDBConnectionResponse")]
    void SetDBConnection(string serviceURL);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQLWebService/SetDBConnection", ReplyAction="http://tempuri.org/ISQLWebService/SetDBConnectionResponse")]
    System.Threading.Tasks.Task SetDBConnectionAsync(string serviceURL);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQLWebService/GetData", ReplyAction="http://tempuri.org/ISQLWebService/GetDataResponse")]
    string GetData(string query, string AuthKey);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQLWebService/GetData", ReplyAction="http://tempuri.org/ISQLWebService/GetDataResponse")]
    System.Threading.Tasks.Task<string> GetDataAsync(string query, string AuthKey);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQLWebService/GetSQLPlan", ReplyAction="http://tempuri.org/ISQLWebService/GetSQLPlanResponse")]
    string GetSQLPlan(string query);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQLWebService/GetSQLPlan", ReplyAction="http://tempuri.org/ISQLWebService/GetSQLPlanResponse")]
    System.Threading.Tasks.Task<string> GetSQLPlanAsync(string query);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQLWebService/GetTime", ReplyAction="http://tempuri.org/ISQLWebService/GetTimeResponse")]
    System.DateTime GetTime();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQLWebService/GetTime", ReplyAction="http://tempuri.org/ISQLWebService/GetTimeResponse")]
    System.Threading.Tasks.Task<System.DateTime> GetTimeAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQLWebService/RegistQuery", ReplyAction="http://tempuri.org/ISQLWebService/RegistQueryResponse")]
    void RegistQuery(string AuthKey, string query);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQLWebService/RegistQuery", ReplyAction="http://tempuri.org/ISQLWebService/RegistQueryResponse")]
    System.Threading.Tasks.Task RegistQueryAsync(string AuthKey, string query);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQLWebService/RegistQueryBlock", ReplyAction="http://tempuri.org/ISQLWebService/RegistQueryBlockResponse")]
    void RegistQueryBlock(string AuthKey, string[] QueryBlock);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQLWebService/RegistQueryBlock", ReplyAction="http://tempuri.org/ISQLWebService/RegistQueryBlockResponse")]
    System.Threading.Tasks.Task RegistQueryBlockAsync(string AuthKey, string[] QueryBlock);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISQLWebServiceCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISQLWebService/OnJobEnd")]
    void OnJobEnd(string message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISQLWebServiceChannel : ISQLWebService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SQLWebServiceClient : System.ServiceModel.DuplexClientBase<ISQLWebService>, ISQLWebService
{
    
    public SQLWebServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public SQLWebServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public SQLWebServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public SQLWebServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public SQLWebServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public void SetClientCallbackProxy()
    {
        base.Channel.SetClientCallbackProxy();
    }
    
    public System.Threading.Tasks.Task SetClientCallbackProxyAsync()
    {
        return base.Channel.SetClientCallbackProxyAsync();
    }
    
    public void SetDBConnection(string serviceURL)
    {
        base.Channel.SetDBConnection(serviceURL);
    }
    
    public System.Threading.Tasks.Task SetDBConnectionAsync(string serviceURL)
    {
        return base.Channel.SetDBConnectionAsync(serviceURL);
    }
    
    public string GetData(string query, string AuthKey)
    {
        return base.Channel.GetData(query, AuthKey);
    }
    
    public System.Threading.Tasks.Task<string> GetDataAsync(string query, string AuthKey)
    {
        return base.Channel.GetDataAsync(query, AuthKey);
    }
    
    public string GetSQLPlan(string query)
    {
        return base.Channel.GetSQLPlan(query);
    }
    
    public System.Threading.Tasks.Task<string> GetSQLPlanAsync(string query)
    {
        return base.Channel.GetSQLPlanAsync(query);
    }
    
    public System.DateTime GetTime()
    {
        return base.Channel.GetTime();
    }
    
    public System.Threading.Tasks.Task<System.DateTime> GetTimeAsync()
    {
        return base.Channel.GetTimeAsync();
    }
    
    public void RegistQuery(string AuthKey, string query)
    {
        base.Channel.RegistQuery(AuthKey, query);
    }
    
    public System.Threading.Tasks.Task RegistQueryAsync(string AuthKey, string query)
    {
        return base.Channel.RegistQueryAsync(AuthKey, query);
    }
    
    public void RegistQueryBlock(string AuthKey, string[] QueryBlock)
    {
        base.Channel.RegistQueryBlock(AuthKey, QueryBlock);
    }
    
    public System.Threading.Tasks.Task RegistQueryBlockAsync(string AuthKey, string[] QueryBlock)
    {
        return base.Channel.RegistQueryBlockAsync(AuthKey, QueryBlock);
    }
}
