//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18449
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceServer.WebServiceVO.Settings
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyCompany", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.WebServiceVO.Settings")]
    public partial class MyCompany : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string B_NField;
        
        private string RegistryNumberField;
        
        private string businessTypeField;
        
        private string chairManField;
        
        private string emailField;
        
        private string etcField;
        
        private string faxField;
        
        private string homePageField;
        
        private string licenceField;
        
        private string myDetailAddressField;
        
        private string myNameField;
        
        private string myPostNoField;
        
        private string phoneField;
        
        private string startDateField;
        
        private string subB_NField;
        
        private string subBusinessTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string B_N
        {
            get
            {
                return this.B_NField;
            }
            set
            {
                this.B_NField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistryNumber
        {
            get
            {
                return this.RegistryNumberField;
            }
            set
            {
                this.RegistryNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string businessType
        {
            get
            {
                return this.businessTypeField;
            }
            set
            {
                this.businessTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string chairMan
        {
            get
            {
                return this.chairManField;
            }
            set
            {
                this.chairManField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string etc
        {
            get
            {
                return this.etcField;
            }
            set
            {
                this.etcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string homePage
        {
            get
            {
                return this.homePageField;
            }
            set
            {
                this.homePageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string licence
        {
            get
            {
                return this.licenceField;
            }
            set
            {
                this.licenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string myDetailAddress
        {
            get
            {
                return this.myDetailAddressField;
            }
            set
            {
                this.myDetailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string myName
        {
            get
            {
                return this.myNameField;
            }
            set
            {
                this.myNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string myPostNo
        {
            get
            {
                return this.myPostNoField;
            }
            set
            {
                this.myPostNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subB_N
        {
            get
            {
                return this.subB_NField;
            }
            set
            {
                this.subB_NField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subBusinessType
        {
            get
            {
                return this.subBusinessTypeField;
            }
            set
            {
                this.subBusinessTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonSettings", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.WebServiceVO.Settings")]
    public partial class CommonSettings : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WebServiceServer.Enums.가용재고관리 가용재고관리Field;
        
        private WebServiceServer.Enums.기본단가 기본단가Field;
        
        private WebServiceServer.Enums.기본작업메뉴 기본작업메뉴Field;
        
        private WebServiceServer.Enums.반품처리시_수발주정리 반품처리시_수발주정리Field;
        
        private WebServiceServer.Enums.사원매입관리 사원매입관리Field;
        
        private WebServiceServer.Enums.사원판매관리 사원판매관리Field;
        
        private WebServiceServer.Enums.상품등록_안된_품목처리 상품등록_안된_품목처리Field;
        
        private WebServiceServer.Enums.상품조회창에_매입가_표시 상품조회창에_매입가_표시Field;
        
        private WebServiceServer.Enums.재고부족분_경고 재고부족분_경고Field;
        
        private WebServiceServer.Enums.재고액평가법 재고액평가법Field;
        
        private WebServiceServer.Enums.조회창크기 조회창크기Field;
        
        private WebServiceServer.Enums.창고관리 창고관리Field;
        
        private WebServiceServer.Enums.판매_매입분의_회계처리 판매_매입분의_회계처리Field;
        
        private WebServiceServer.Enums.판매시_세트자료_조립해체 판매시_세트자료_조립해체Field;
        
        private WebServiceServer.Enums.판매처리시_점검 판매처리시_점검Field;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.가용재고관리 가용재고관리
        {
            get
            {
                return this.가용재고관리Field;
            }
            set
            {
                this.가용재고관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.기본단가 기본단가
        {
            get
            {
                return this.기본단가Field;
            }
            set
            {
                this.기본단가Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.기본작업메뉴 기본작업메뉴
        {
            get
            {
                return this.기본작업메뉴Field;
            }
            set
            {
                this.기본작업메뉴Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.반품처리시_수발주정리 반품처리시_수발주정리
        {
            get
            {
                return this.반품처리시_수발주정리Field;
            }
            set
            {
                this.반품처리시_수발주정리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사원매입관리 사원매입관리
        {
            get
            {
                return this.사원매입관리Field;
            }
            set
            {
                this.사원매입관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사원판매관리 사원판매관리
        {
            get
            {
                return this.사원판매관리Field;
            }
            set
            {
                this.사원판매관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.상품등록_안된_품목처리 상품등록_안된_품목처리
        {
            get
            {
                return this.상품등록_안된_품목처리Field;
            }
            set
            {
                this.상품등록_안된_품목처리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.상품조회창에_매입가_표시 상품조회창에_매입가_표시
        {
            get
            {
                return this.상품조회창에_매입가_표시Field;
            }
            set
            {
                this.상품조회창에_매입가_표시Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.재고부족분_경고 재고부족분_경고
        {
            get
            {
                return this.재고부족분_경고Field;
            }
            set
            {
                this.재고부족분_경고Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.재고액평가법 재고액평가법
        {
            get
            {
                return this.재고액평가법Field;
            }
            set
            {
                this.재고액평가법Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.조회창크기 조회창크기
        {
            get
            {
                return this.조회창크기Field;
            }
            set
            {
                this.조회창크기Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.창고관리 창고관리
        {
            get
            {
                return this.창고관리Field;
            }
            set
            {
                this.창고관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.판매_매입분의_회계처리 판매_매입분의_회계처리
        {
            get
            {
                return this.판매_매입분의_회계처리Field;
            }
            set
            {
                this.판매_매입분의_회계처리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.판매시_세트자료_조립해체 판매시_세트자료_조립해체
        {
            get
            {
                return this.판매시_세트자료_조립해체Field;
            }
            set
            {
                this.판매시_세트자료_조립해체Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.판매처리시_점검 판매처리시_점검
        {
            get
            {
                return this.판매처리시_점검Field;
            }
            set
            {
                this.판매처리시_점검Field = value;
            }
        }
    }
}
namespace WebServiceServer.Enums
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="가용재고관리", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 가용재고관리 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        관리함 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        관리안함 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="기본단가", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 기본단가 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        최종단가 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        표준단가 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        적용단가 = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="기본작업메뉴", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 기본작업메뉴 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        거래명세서 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        견적서 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        견적의뢰서 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        발주서 = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="반품처리시_수발주정리", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 반품처리시_수발주정리 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        처리여부선택 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        수량합계표시 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="사원매입관리", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 사원매입관리 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        업체담당자로 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        판매시마다입력 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="사원판매관리", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 사원판매관리 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        업체담당자로 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        판매시마다입력 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="상품등록_안된_품목처리", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 상품등록_안된_품목처리 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        가능 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        불가능 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="상품조회창에_매입가_표시", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 상품조회창에_매입가_표시 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        표시 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        표시안함 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="재고부족분_경고", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 재고부족분_경고 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        경고 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        경고안함 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        품명조회창에_재고표기 = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="재고액평가법", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 재고액평가법 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        이동평균법 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        표준단가 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        최종매입싯가법 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        표준비교안함 = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="조회창크기", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 조회창크기 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        보통 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        크게 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="창고관리", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 창고관리 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        관리안함 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        관리함 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="판매_매입분의_회계처리", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 판매_매입분의_회계처리 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        해당업체로 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        본사가_있는_경우_본사로 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="판매시_세트자료_조립해체", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 판매시_세트자료_조립해체 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        이행 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        미이행 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="판매처리시_점검", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 판매처리시_점검 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        설정안됨 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        미수금_자동출고정지 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        확인후_출고정지 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        관리안함 = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnitCostType", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum UnitCostType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        매입 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        매출 = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="사용자권한", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 사용자권한 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        관리불가 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        조회만가능 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        모두허용 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="사용자등급", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.Enums")]
    public enum 사용자등급 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        페기 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        관리자 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        일반사용자 = 2,
    }
}
namespace WebServiceServer.WebServiceVO.Goods
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodsListVO", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.WebServiceVO.Goods")]
    public partial class GoodsListVO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string good_imageField;
        
        private string good_makerField;
        
        private string good_nameField;
        
        private string good_nicknameField;
        
        private long good_pkField;
        
        private string good_subnameField;
        
        private string statusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string good_image
        {
            get
            {
                return this.good_imageField;
            }
            set
            {
                this.good_imageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string good_maker
        {
            get
            {
                return this.good_makerField;
            }
            set
            {
                this.good_makerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string good_name
        {
            get
            {
                return this.good_nameField;
            }
            set
            {
                this.good_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string good_nickname
        {
            get
            {
                return this.good_nicknameField;
            }
            set
            {
                this.good_nicknameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long good_pk
        {
            get
            {
                return this.good_pkField;
            }
            set
            {
                this.good_pkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string good_subname
        {
            get
            {
                return this.good_subnameField;
            }
            set
            {
                this.good_subnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodsDetail", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.WebServiceVO.Goods")]
    public partial class GoodsDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string etc_infoField;
        
        private string good_imageField;
        
        private string good_makerField;
        
        private string good_nameField;
        
        private string good_nicknameField;
        
        private long good_pkField;
        
        private string good_subnameField;
        
        private WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.good_unit_info[] good_unit_infoListField;
        
        private WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.goodpart[] goodpartListField;
        
        private WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.goodseller[] goodsellerListField;
        
        private long properstockField;
        
        private string statusField;
        
        private WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.unitcost[] unitcostListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string etc_info
        {
            get
            {
                return this.etc_infoField;
            }
            set
            {
                this.etc_infoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string good_image
        {
            get
            {
                return this.good_imageField;
            }
            set
            {
                this.good_imageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string good_maker
        {
            get
            {
                return this.good_makerField;
            }
            set
            {
                this.good_makerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string good_name
        {
            get
            {
                return this.good_nameField;
            }
            set
            {
                this.good_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string good_nickname
        {
            get
            {
                return this.good_nicknameField;
            }
            set
            {
                this.good_nicknameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long good_pk
        {
            get
            {
                return this.good_pkField;
            }
            set
            {
                this.good_pkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string good_subname
        {
            get
            {
                return this.good_subnameField;
            }
            set
            {
                this.good_subnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.good_unit_info[] good_unit_infoList
        {
            get
            {
                return this.good_unit_infoListField;
            }
            set
            {
                this.good_unit_infoListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.goodpart[] goodpartList
        {
            get
            {
                return this.goodpartListField;
            }
            set
            {
                this.goodpartListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.goodseller[] goodsellerList
        {
            get
            {
                return this.goodsellerListField;
            }
            set
            {
                this.goodsellerListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long properstock
        {
            get
            {
                return this.properstockField;
            }
            set
            {
                this.properstockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.unitcost[] unitcostList
        {
            get
            {
                return this.unitcostListField;
            }
            set
            {
                this.unitcostListField = value;
            }
        }
    }
}
namespace WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="good_unit_info", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.WebServiceVO.Goods.GoodD" +
        "etail_Sub")]
    public partial class good_unit_info : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long amountField;
        
        private string flag_unitField;
        
        private long good_idxField;
        
        private string unitField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string flag_unit
        {
            get
            {
                return this.flag_unitField;
            }
            set
            {
                this.flag_unitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long good_idx
        {
            get
            {
                return this.good_idxField;
            }
            set
            {
                this.good_idxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="goodpart", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.WebServiceVO.Goods.GoodD" +
        "etail_Sub")]
    public partial class goodpart : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long final_good_idxField;
        
        private long required_amountField;
        
        private long required_goodField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long final_good_idx
        {
            get
            {
                return this.final_good_idxField;
            }
            set
            {
                this.final_good_idxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long required_amount
        {
            get
            {
                return this.required_amountField;
            }
            set
            {
                this.required_amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long required_good
        {
            get
            {
                return this.required_goodField;
            }
            set
            {
                this.required_goodField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="goodseller", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.WebServiceVO.Goods.GoodD" +
        "etail_Sub")]
    public partial class goodseller : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string company_addrField;
        
        private string company_faxField;
        
        private string company_nameField;
        
        private string company_phoneField;
        
        private int company_worktimeField;
        
        private long goods_idxField;
        
        private long seller_idxField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string company_addr
        {
            get
            {
                return this.company_addrField;
            }
            set
            {
                this.company_addrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string company_fax
        {
            get
            {
                return this.company_faxField;
            }
            set
            {
                this.company_faxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string company_name
        {
            get
            {
                return this.company_nameField;
            }
            set
            {
                this.company_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string company_phone
        {
            get
            {
                return this.company_phoneField;
            }
            set
            {
                this.company_phoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int company_worktime
        {
            get
            {
                return this.company_worktimeField;
            }
            set
            {
                this.company_worktimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long goods_idx
        {
            get
            {
                return this.goods_idxField;
            }
            set
            {
                this.goods_idxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long seller_idx
        {
            get
            {
                return this.seller_idxField;
            }
            set
            {
                this.seller_idxField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="unitcost", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.WebServiceVO.Goods.GoodD" +
        "etail_Sub")]
    public partial class unitcost : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long company_idxField;
        
        private bool contain_taxField;
        
        private long costField;
        
        private WebServiceServer.Enums.UnitCostType cost_typeField;
        
        private long good_idxField;
        
        private bool is_free_taxField;
        
        private string unitField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long company_idx
        {
            get
            {
                return this.company_idxField;
            }
            set
            {
                this.company_idxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool contain_tax
        {
            get
            {
                return this.contain_taxField;
            }
            set
            {
                this.contain_taxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long cost
        {
            get
            {
                return this.costField;
            }
            set
            {
                this.costField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.UnitCostType cost_type
        {
            get
            {
                return this.cost_typeField;
            }
            set
            {
                this.cost_typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long good_idx
        {
            get
            {
                return this.good_idxField;
            }
            set
            {
                this.good_idxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_free_tax
        {
            get
            {
                return this.is_free_taxField;
            }
            set
            {
                this.is_free_taxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
    }
}
namespace WebServiceServer.WebServiceVO.Users
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsersVO", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.WebServiceVO.Users")]
    public partial class UsersVO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WebServiceServer.WebServiceVO.Users.UserAuth UserAuthField;
        
        private string UserIDField;
        
        private string UserPasswordField;
        
        private WebServiceServer.Enums.사용자등급 UserTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.WebServiceVO.Users.UserAuth UserAuth
        {
            get
            {
                return this.UserAuthField;
            }
            set
            {
                this.UserAuthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword
        {
            get
            {
                return this.UserPasswordField;
            }
            set
            {
                this.UserPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자등급 UserType
        {
            get
            {
                return this.UserTypeField;
            }
            set
            {
                this.UserTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAuth", Namespace="http://schemas.datacontract.org/2004/07/WebServiceServer.WebServiceVO.Users")]
    public partial class UserAuth : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WebServiceServer.Enums.사용자권한 견적관리Field;
        
        private WebServiceServer.Enums.사용자권한 계정관리Field;
        
        private WebServiceServer.Enums.사용자권한 고객정보Field;
        
        private WebServiceServer.Enums.사용자권한 나의정보관리Field;
        
        private WebServiceServer.Enums.사용자권한 데이터관리Field;
        
        private WebServiceServer.Enums.사용자권한 매입관리Field;
        
        private WebServiceServer.Enums.사용자권한 상품정보Field;
        
        private WebServiceServer.Enums.사용자권한 설정관리Field;
        
        private WebServiceServer.Enums.사용자권한 세금계산서관리Field;
        
        private WebServiceServer.Enums.사용자권한 양식정보Field;
        
        private WebServiceServer.Enums.사용자권한 에프터서비스관리Field;
        
        private WebServiceServer.Enums.사용자권한 인사관리Field;
        
        private WebServiceServer.Enums.사용자권한 일정관리Field;
        
        private WebServiceServer.Enums.사용자권한 재고관리Field;
        
        private WebServiceServer.Enums.사용자권한 판매관리Field;
        
        private WebServiceServer.Enums.사용자권한 표준관리Field;
        
        private WebServiceServer.Enums.사용자권한 회계관리Field;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 견적관리
        {
            get
            {
                return this.견적관리Field;
            }
            set
            {
                this.견적관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 계정관리
        {
            get
            {
                return this.계정관리Field;
            }
            set
            {
                this.계정관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 고객정보
        {
            get
            {
                return this.고객정보Field;
            }
            set
            {
                this.고객정보Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 나의정보관리
        {
            get
            {
                return this.나의정보관리Field;
            }
            set
            {
                this.나의정보관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 데이터관리
        {
            get
            {
                return this.데이터관리Field;
            }
            set
            {
                this.데이터관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 매입관리
        {
            get
            {
                return this.매입관리Field;
            }
            set
            {
                this.매입관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 상품정보
        {
            get
            {
                return this.상품정보Field;
            }
            set
            {
                this.상품정보Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 설정관리
        {
            get
            {
                return this.설정관리Field;
            }
            set
            {
                this.설정관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 세금계산서관리
        {
            get
            {
                return this.세금계산서관리Field;
            }
            set
            {
                this.세금계산서관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 양식정보
        {
            get
            {
                return this.양식정보Field;
            }
            set
            {
                this.양식정보Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 에프터서비스관리
        {
            get
            {
                return this.에프터서비스관리Field;
            }
            set
            {
                this.에프터서비스관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 인사관리
        {
            get
            {
                return this.인사관리Field;
            }
            set
            {
                this.인사관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 일정관리
        {
            get
            {
                return this.일정관리Field;
            }
            set
            {
                this.일정관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 재고관리
        {
            get
            {
                return this.재고관리Field;
            }
            set
            {
                this.재고관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 판매관리
        {
            get
            {
                return this.판매관리Field;
            }
            set
            {
                this.판매관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 표준관리
        {
            get
            {
                return this.표준관리Field;
            }
            set
            {
                this.표준관리Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceServer.Enums.사용자권한 회계관리
        {
            get
            {
                return this.회계관리Field;
            }
            set
            {
                this.회계관리Field = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWebService")]
public interface IWebService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetData", ReplyAction="http://tempuri.org/IWebService/GetDataResponse")]
    string GetData(string AuthKey, string query, string serviceURL);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetData", ReplyAction="http://tempuri.org/IWebService/GetDataResponse")]
    System.Threading.Tasks.Task<string> GetDataAsync(string AuthKey, string query, string serviceURL);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetTime", ReplyAction="http://tempuri.org/IWebService/GetTimeResponse")]
    System.DateTime GetTime();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetTime", ReplyAction="http://tempuri.org/IWebService/GetTimeResponse")]
    System.Threading.Tasks.Task<System.DateTime> GetTimeAsync();
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWebService/RegistQuery")]
    void RegistQuery(string AuthKey, string query, string serviceURL);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWebService/RegistQuery")]
    System.Threading.Tasks.Task RegistQueryAsync(string AuthKey, string query, string serviceURL);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWebService/RegistQueryBlock")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Settings.MyCompany))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Settings.CommonSettings))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Goods.GoodsListVO[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Goods.GoodsListVO))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Goods.GoodsDetail))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.good_unit_info[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.good_unit_info))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.goodpart[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.goodpart))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.goodseller[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.goodseller))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.unitcost[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Goods.GoodDetail_Sub.unitcost))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.사용자권한))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.사용자등급))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.가용재고관리))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.기본단가))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.기본작업메뉴))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.반품처리시_수발주정리))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.사원매입관리))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.사원판매관리))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.상품등록_안된_품목처리))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.상품조회창에_매입가_표시))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.재고부족분_경고))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.재고액평가법))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.조회창크기))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.창고관리))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.판매_매입분의_회계처리))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.판매시_세트자료_조립해체))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.판매처리시_점검))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.Enums.UnitCostType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Users.UsersVO))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Users.UserAuth))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WebServiceServer.WebServiceVO.Users.UsersVO[]))]
    void RegistQueryBlock(string AuthKey, object[] QueryBlock, string serviceURL);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWebService/RegistQueryBlock")]
    System.Threading.Tasks.Task RegistQueryBlockAsync(string AuthKey, object[] QueryBlock, string serviceURL);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UserLogIn", ReplyAction="http://tempuri.org/IWebService/UserLogInResponse")]
    WebServiceServer.WebServiceVO.Users.UsersVO UserLogIn(string AuthKey, string serviceURL, string id, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UserLogIn", ReplyAction="http://tempuri.org/IWebService/UserLogInResponse")]
    System.Threading.Tasks.Task<WebServiceServer.WebServiceVO.Users.UsersVO> UserLogInAsync(string AuthKey, string serviceURL, string id, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetUserInfo", ReplyAction="http://tempuri.org/IWebService/GetUserInfoResponse")]
    WebServiceServer.WebServiceVO.Users.UsersVO GetUserInfo(string AuthKey, string serviceURL, string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetUserInfo", ReplyAction="http://tempuri.org/IWebService/GetUserInfoResponse")]
    System.Threading.Tasks.Task<WebServiceServer.WebServiceVO.Users.UsersVO> GetUserInfoAsync(string AuthKey, string serviceURL, string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetUsersInfo", ReplyAction="http://tempuri.org/IWebService/GetUsersInfoResponse")]
    WebServiceServer.WebServiceVO.Users.UsersVO[] GetUsersInfo(string AuthKey, string serviceURL);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetUsersInfo", ReplyAction="http://tempuri.org/IWebService/GetUsersInfoResponse")]
    System.Threading.Tasks.Task<WebServiceServer.WebServiceVO.Users.UsersVO[]> GetUsersInfoAsync(string AuthKey, string serviceURL);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdateUserInfo", ReplyAction="http://tempuri.org/IWebService/UpdateUserInfoResponse")]
    int UpdateUserInfo(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Users.UsersVO userInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdateUserInfo", ReplyAction="http://tempuri.org/IWebService/UpdateUserInfoResponse")]
    System.Threading.Tasks.Task<int> UpdateUserInfoAsync(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Users.UsersVO userInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/InsertUserInfo", ReplyAction="http://tempuri.org/IWebService/InsertUserInfoResponse")]
    int InsertUserInfo(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Users.UsersVO userInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/InsertUserInfo", ReplyAction="http://tempuri.org/IWebService/InsertUserInfoResponse")]
    System.Threading.Tasks.Task<int> InsertUserInfoAsync(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Users.UsersVO userInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetMyCompanyInfo", ReplyAction="http://tempuri.org/IWebService/GetMyCompanyInfoResponse")]
    WebServiceServer.WebServiceVO.Settings.MyCompany GetMyCompanyInfo(string AuthKey, string serviceURL);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetMyCompanyInfo", ReplyAction="http://tempuri.org/IWebService/GetMyCompanyInfoResponse")]
    System.Threading.Tasks.Task<WebServiceServer.WebServiceVO.Settings.MyCompany> GetMyCompanyInfoAsync(string AuthKey, string serviceURL);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/SetMyCompanyInfo", ReplyAction="http://tempuri.org/IWebService/SetMyCompanyInfoResponse")]
    int SetMyCompanyInfo(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Settings.MyCompany myCompanyInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/SetMyCompanyInfo", ReplyAction="http://tempuri.org/IWebService/SetMyCompanyInfoResponse")]
    System.Threading.Tasks.Task<int> SetMyCompanyInfoAsync(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Settings.MyCompany myCompanyInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCommonSettingInfo", ReplyAction="http://tempuri.org/IWebService/GetCommonSettingInfoResponse")]
    WebServiceServer.WebServiceVO.Settings.CommonSettings GetCommonSettingInfo(string AuthKey, string serviceURL);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCommonSettingInfo", ReplyAction="http://tempuri.org/IWebService/GetCommonSettingInfoResponse")]
    System.Threading.Tasks.Task<WebServiceServer.WebServiceVO.Settings.CommonSettings> GetCommonSettingInfoAsync(string AuthKey, string serviceURL);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/SetCommonSettingInfo", ReplyAction="http://tempuri.org/IWebService/SetCommonSettingInfoResponse")]
    int SetCommonSettingInfo(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Settings.CommonSettings CommonSettings);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/SetCommonSettingInfo", ReplyAction="http://tempuri.org/IWebService/SetCommonSettingInfoResponse")]
    System.Threading.Tasks.Task<int> SetCommonSettingInfoAsync(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Settings.CommonSettings CommonSettings);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetGoodsCount", ReplyAction="http://tempuri.org/IWebService/GetGoodsCountResponse")]
    long GetGoodsCount(string AuthKey, string serviceURL, string good_name, string good_subName, string good_NickName, string good_maker);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetGoodsCount", ReplyAction="http://tempuri.org/IWebService/GetGoodsCountResponse")]
    System.Threading.Tasks.Task<long> GetGoodsCountAsync(string AuthKey, string serviceURL, string good_name, string good_subName, string good_NickName, string good_maker);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetGoodsList", ReplyAction="http://tempuri.org/IWebService/GetGoodsListResponse")]
    WebServiceServer.WebServiceVO.Goods.GoodsListVO[] GetGoodsList(string AuthKey, string serviceURL, int page, int rowCount, string good_name, string good_subName, string good_NickName, string good_maker);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetGoodsList", ReplyAction="http://tempuri.org/IWebService/GetGoodsListResponse")]
    System.Threading.Tasks.Task<WebServiceServer.WebServiceVO.Goods.GoodsListVO[]> GetGoodsListAsync(string AuthKey, string serviceURL, int page, int rowCount, string good_name, string good_subName, string good_NickName, string good_maker);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetGoodDetail", ReplyAction="http://tempuri.org/IWebService/GetGoodDetailResponse")]
    WebServiceServer.WebServiceVO.Goods.GoodsDetail GetGoodDetail(string AuthKey, string serviceURL, long good_pk);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetGoodDetail", ReplyAction="http://tempuri.org/IWebService/GetGoodDetailResponse")]
    System.Threading.Tasks.Task<WebServiceServer.WebServiceVO.Goods.GoodsDetail> GetGoodDetailAsync(string AuthKey, string serviceURL, long good_pk);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/InsertGood", ReplyAction="http://tempuri.org/IWebService/InsertGoodResponse")]
    int InsertGood(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Goods.GoodsDetail goodInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/InsertGood", ReplyAction="http://tempuri.org/IWebService/InsertGoodResponse")]
    System.Threading.Tasks.Task<int> InsertGoodAsync(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Goods.GoodsDetail goodInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdateGood", ReplyAction="http://tempuri.org/IWebService/UpdateGoodResponse")]
    int UpdateGood(string AuthKey, string query, string serviceURL, WebServiceServer.WebServiceVO.Goods.GoodsDetail goodInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdateGood", ReplyAction="http://tempuri.org/IWebService/UpdateGoodResponse")]
    System.Threading.Tasks.Task<int> UpdateGoodAsync(string AuthKey, string query, string serviceURL, WebServiceServer.WebServiceVO.Goods.GoodsDetail goodInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/DeleteGood", ReplyAction="http://tempuri.org/IWebService/DeleteGoodResponse")]
    int DeleteGood(string AuthKey, string query, string serviceURL, long goodIDX);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/DeleteGood", ReplyAction="http://tempuri.org/IWebService/DeleteGoodResponse")]
    System.Threading.Tasks.Task<int> DeleteGoodAsync(string AuthKey, string query, string serviceURL, long goodIDX);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWebServiceChannel : IWebService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WebServiceClient : System.ServiceModel.ClientBase<IWebService>, IWebService
{
    
    public WebServiceClient()
    {
    }
    
    public WebServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WebServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetData(string AuthKey, string query, string serviceURL)
    {
        return base.Channel.GetData(AuthKey, query, serviceURL);
    }
    
    public System.Threading.Tasks.Task<string> GetDataAsync(string AuthKey, string query, string serviceURL)
    {
        return base.Channel.GetDataAsync(AuthKey, query, serviceURL);
    }
    
    public System.DateTime GetTime()
    {
        return base.Channel.GetTime();
    }
    
    public System.Threading.Tasks.Task<System.DateTime> GetTimeAsync()
    {
        return base.Channel.GetTimeAsync();
    }
    
    public void RegistQuery(string AuthKey, string query, string serviceURL)
    {
        base.Channel.RegistQuery(AuthKey, query, serviceURL);
    }
    
    public System.Threading.Tasks.Task RegistQueryAsync(string AuthKey, string query, string serviceURL)
    {
        return base.Channel.RegistQueryAsync(AuthKey, query, serviceURL);
    }
    
    public void RegistQueryBlock(string AuthKey, object[] QueryBlock, string serviceURL)
    {
        base.Channel.RegistQueryBlock(AuthKey, QueryBlock, serviceURL);
    }
    
    public System.Threading.Tasks.Task RegistQueryBlockAsync(string AuthKey, object[] QueryBlock, string serviceURL)
    {
        return base.Channel.RegistQueryBlockAsync(AuthKey, QueryBlock, serviceURL);
    }
    
    public WebServiceServer.WebServiceVO.Users.UsersVO UserLogIn(string AuthKey, string serviceURL, string id, string password)
    {
        return base.Channel.UserLogIn(AuthKey, serviceURL, id, password);
    }
    
    public System.Threading.Tasks.Task<WebServiceServer.WebServiceVO.Users.UsersVO> UserLogInAsync(string AuthKey, string serviceURL, string id, string password)
    {
        return base.Channel.UserLogInAsync(AuthKey, serviceURL, id, password);
    }
    
    public WebServiceServer.WebServiceVO.Users.UsersVO GetUserInfo(string AuthKey, string serviceURL, string id)
    {
        return base.Channel.GetUserInfo(AuthKey, serviceURL, id);
    }
    
    public System.Threading.Tasks.Task<WebServiceServer.WebServiceVO.Users.UsersVO> GetUserInfoAsync(string AuthKey, string serviceURL, string id)
    {
        return base.Channel.GetUserInfoAsync(AuthKey, serviceURL, id);
    }
    
    public WebServiceServer.WebServiceVO.Users.UsersVO[] GetUsersInfo(string AuthKey, string serviceURL)
    {
        return base.Channel.GetUsersInfo(AuthKey, serviceURL);
    }
    
    public System.Threading.Tasks.Task<WebServiceServer.WebServiceVO.Users.UsersVO[]> GetUsersInfoAsync(string AuthKey, string serviceURL)
    {
        return base.Channel.GetUsersInfoAsync(AuthKey, serviceURL);
    }
    
    public int UpdateUserInfo(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Users.UsersVO userInfo)
    {
        return base.Channel.UpdateUserInfo(AuthKey, serviceURL, userInfo);
    }
    
    public System.Threading.Tasks.Task<int> UpdateUserInfoAsync(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Users.UsersVO userInfo)
    {
        return base.Channel.UpdateUserInfoAsync(AuthKey, serviceURL, userInfo);
    }
    
    public int InsertUserInfo(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Users.UsersVO userInfo)
    {
        return base.Channel.InsertUserInfo(AuthKey, serviceURL, userInfo);
    }
    
    public System.Threading.Tasks.Task<int> InsertUserInfoAsync(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Users.UsersVO userInfo)
    {
        return base.Channel.InsertUserInfoAsync(AuthKey, serviceURL, userInfo);
    }
    
    public WebServiceServer.WebServiceVO.Settings.MyCompany GetMyCompanyInfo(string AuthKey, string serviceURL)
    {
        return base.Channel.GetMyCompanyInfo(AuthKey, serviceURL);
    }
    
    public System.Threading.Tasks.Task<WebServiceServer.WebServiceVO.Settings.MyCompany> GetMyCompanyInfoAsync(string AuthKey, string serviceURL)
    {
        return base.Channel.GetMyCompanyInfoAsync(AuthKey, serviceURL);
    }
    
    public int SetMyCompanyInfo(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Settings.MyCompany myCompanyInfo)
    {
        return base.Channel.SetMyCompanyInfo(AuthKey, serviceURL, myCompanyInfo);
    }
    
    public System.Threading.Tasks.Task<int> SetMyCompanyInfoAsync(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Settings.MyCompany myCompanyInfo)
    {
        return base.Channel.SetMyCompanyInfoAsync(AuthKey, serviceURL, myCompanyInfo);
    }
    
    public WebServiceServer.WebServiceVO.Settings.CommonSettings GetCommonSettingInfo(string AuthKey, string serviceURL)
    {
        return base.Channel.GetCommonSettingInfo(AuthKey, serviceURL);
    }
    
    public System.Threading.Tasks.Task<WebServiceServer.WebServiceVO.Settings.CommonSettings> GetCommonSettingInfoAsync(string AuthKey, string serviceURL)
    {
        return base.Channel.GetCommonSettingInfoAsync(AuthKey, serviceURL);
    }
    
    public int SetCommonSettingInfo(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Settings.CommonSettings CommonSettings)
    {
        return base.Channel.SetCommonSettingInfo(AuthKey, serviceURL, CommonSettings);
    }
    
    public System.Threading.Tasks.Task<int> SetCommonSettingInfoAsync(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Settings.CommonSettings CommonSettings)
    {
        return base.Channel.SetCommonSettingInfoAsync(AuthKey, serviceURL, CommonSettings);
    }
    
    public long GetGoodsCount(string AuthKey, string serviceURL, string good_name, string good_subName, string good_NickName, string good_maker)
    {
        return base.Channel.GetGoodsCount(AuthKey, serviceURL, good_name, good_subName, good_NickName, good_maker);
    }
    
    public System.Threading.Tasks.Task<long> GetGoodsCountAsync(string AuthKey, string serviceURL, string good_name, string good_subName, string good_NickName, string good_maker)
    {
        return base.Channel.GetGoodsCountAsync(AuthKey, serviceURL, good_name, good_subName, good_NickName, good_maker);
    }
    
    public WebServiceServer.WebServiceVO.Goods.GoodsListVO[] GetGoodsList(string AuthKey, string serviceURL, int page, int rowCount, string good_name, string good_subName, string good_NickName, string good_maker)
    {
        return base.Channel.GetGoodsList(AuthKey, serviceURL, page, rowCount, good_name, good_subName, good_NickName, good_maker);
    }
    
    public System.Threading.Tasks.Task<WebServiceServer.WebServiceVO.Goods.GoodsListVO[]> GetGoodsListAsync(string AuthKey, string serviceURL, int page, int rowCount, string good_name, string good_subName, string good_NickName, string good_maker)
    {
        return base.Channel.GetGoodsListAsync(AuthKey, serviceURL, page, rowCount, good_name, good_subName, good_NickName, good_maker);
    }
    
    public WebServiceServer.WebServiceVO.Goods.GoodsDetail GetGoodDetail(string AuthKey, string serviceURL, long good_pk)
    {
        return base.Channel.GetGoodDetail(AuthKey, serviceURL, good_pk);
    }
    
    public System.Threading.Tasks.Task<WebServiceServer.WebServiceVO.Goods.GoodsDetail> GetGoodDetailAsync(string AuthKey, string serviceURL, long good_pk)
    {
        return base.Channel.GetGoodDetailAsync(AuthKey, serviceURL, good_pk);
    }
    
    public int InsertGood(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Goods.GoodsDetail goodInfo)
    {
        return base.Channel.InsertGood(AuthKey, serviceURL, goodInfo);
    }
    
    public System.Threading.Tasks.Task<int> InsertGoodAsync(string AuthKey, string serviceURL, WebServiceServer.WebServiceVO.Goods.GoodsDetail goodInfo)
    {
        return base.Channel.InsertGoodAsync(AuthKey, serviceURL, goodInfo);
    }
    
    public int UpdateGood(string AuthKey, string query, string serviceURL, WebServiceServer.WebServiceVO.Goods.GoodsDetail goodInfo)
    {
        return base.Channel.UpdateGood(AuthKey, query, serviceURL, goodInfo);
    }
    
    public System.Threading.Tasks.Task<int> UpdateGoodAsync(string AuthKey, string query, string serviceURL, WebServiceServer.WebServiceVO.Goods.GoodsDetail goodInfo)
    {
        return base.Channel.UpdateGoodAsync(AuthKey, query, serviceURL, goodInfo);
    }
    
    public int DeleteGood(string AuthKey, string query, string serviceURL, long goodIDX)
    {
        return base.Channel.DeleteGood(AuthKey, query, serviceURL, goodIDX);
    }
    
    public System.Threading.Tasks.Task<int> DeleteGoodAsync(string AuthKey, string query, string serviceURL, long goodIDX)
    {
        return base.Channel.DeleteGoodAsync(AuthKey, query, serviceURL, goodIDX);
    }
}
